### ISSUE TITLE
qual o objetivo desse teste?

### ISSUE THREAD

**Issue by felixmacuiana** [CleidDev/testando#2]
Não estou entender esse teste, alguem pode me explicar

**Comment by CleidDev** [comment]
># Não estou entender esse teste, alguem pode me explicar


*Caro amigo* o teste não esta pronto ainda, sinceras desculpas pela demora na **disponibilização do teste**, ou vocé [pode acessar aqui](https://youtube.com/playlist?list=PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA&si=qugREv1kLR9GtJNA)

![O proprietario Félix Macuiana](https://github.com/CleidDev/testando/assets/161307947/eb92fb88-3eeb-4cf3-b82c-9387a33c3509)

Horario | Sala| Aula |
---|---|---
10:30|Google Classroom| Fundamentos de GitHub
